"""empty message

Revision ID: 35f5f53e1599
Revises:
Create Date: 2023-07-02 19:36:31.817195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35f5f53e1599'
down_revision = None
branch_labels = None
depends_on = None


# ...

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('username', sa.String(length=255), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('password', sa.String(length=255), nullable=False),
                    sa.Column('image_url', sa.String(length=200), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )

    op.add_column('recipes', sa.Column('ingredients', sa.Text(), nullable=False))

    # Create the foreign key constraint after creating the 'users' table
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id_temp', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('recipes_user_id_fkey', 'users', ['user_id_temp'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint('recipes_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id_temp')
        batch_op.drop_column('ingredients')

    op.create_table('recipe',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('title', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.String(length=500), nullable=False),
                    sa.Column('instructions', sa.Text(), nullable=False),
                    sa.Column('prep_time', sa.Integer(), nullable=False),
                    sa.Column('servings', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name='recipe_pkey')
                    )

    op.drop_table('users')
    # ### end Alembic commands ###
